from bot.commands import commands_admin
from bot.commands.commands_downloads import download1
from bot.commands.commands_downloads import download2
from bot.commands.commands_downs import down1
from bot.commands.commands_downs import down2
from bot.commands.commands_downs import down3
from bot.commands.commands_downs import down4
from bot.commands.commands_downs import down5
from bot.commands.commands_other import reset
from bot.commands.commands_other import start
from bot.commands.commands_pars import pars1
from bot.commands.commands_pars import pars2